-- Flyway V15 :: R-26.9 (LEDG-2242)
-- Widen CUSTOMER_ID to 12 and add CURRENCY_CODE. Applied with legacy-ledger 7.0
-- under change request CR-4471.
ALTER TABLE LEDGER.TRANSACTIONS ALTER COLUMN CUSTOMER_ID SET DATA TYPE VARCHAR(12);
ALTER TABLE LEDGER.TRANSACTIONS ADD COLUMN CURRENCY_CODE CHAR(3) NOT NULL DEFAULT 'USD';
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEDGER.TRANSACTIONS');
