-- Flyway V14 :: LEDGER.TRANSACTIONS (Db2 LUW, database LEDGDB)
CREATE TABLE LEDGER.TRANSACTIONS (
    TXN_ID        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID   VARCHAR(10)    NOT NULL,
    AMOUNT        DECIMAL(15, 2) NOT NULL,
    POSTED_AT     TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP
);
